better runner

diff --git a/runner b/runner
--- a/runner
+++ b/runner
@@ -1,23 +1,32 @@
 #!/bin/tcsh
-cd ../src/enzo
-make clean;
-make -j 8;
-##if ( ! $status ) then
+set echo
+set yt_dest = $HOME/local-yt-2014-01-01
+source $yt_dest/bin/activate.csh
+set compile = 0
+if ( $#argv > 0 ) then
+    set compile = 1
+endif
+
+if ( $compile ) then
+    cd ../src/enzo
+    make clean
+    make -j 8;
+    if ( ! $status ) then
+        echo "Compile Failed"
+        exit 1
+    endif
     cd -
-    #test_runner.py --local-dir= /Users/dcollins/scratch/TestRunner  --run-suffix=_CenteredBremoval -o /Users/dcollins/scratch/TestRunner --suite=quick --answer-store --local    --answer-name=_gold_2015-07-31
-test_runner.py --local-dir= /Users/dcollins/scratch/TestRunner  -o /Users/dcollins/scratch/TestRunner \
-     --run-suffix=_CenteredBremoval_arse  \
-        --local    --answer-name=_gold_2015-07-31 --suite=quick #\
-            #      --answer-store 
-        #--problematic=True
-          #--suite=quick
-  #test_runner.py --run-suffix=_CenteredBremoval -o /Users/dcollins/scratch/TestRunner --suite=quick --answer-store --local --local-dir=   --answer-name=_gold_2015-07-31
+endif
 
-#make
-#test_runner.py --run-suffix=_2014-05-18 -o /scratch1/dcollins/TestRunner/dev --suite=push  --answer-store --local --local-dir=/scratch1/dcollins/TestRunner/dev --answer-name=_gold_2014-05-18
+set name = "_E28_enzo-dev"
+set loc = /scratch1/dcollins/TestRunner/dev
+set todo =  --suite=quick 
+set todo = "$todo --answer-store "
+set goldname = _gold_2015-07-31
+set logname = runner_log.`date +"%Y-%m-%d-%H-%M-%S"`
 
-#else 
-#  echo "compile failed"
-#endif
+echo test_runner.py --run-suffix=$name -o $loc $todo --local --local-dir=$loc   --answer-name=$goldname >& $logname
+test_runner.py --run-suffix=$name -o $loc $todo --local --local-dir=$loc   --answer-name=$goldname |& tee -a $logname
+
 
 #end
